"""InvestmentPlan model for storing generated user investment plans."""

from __future__ import annotations

from decimal import Decimal
from typing import TYPE_CHECKING, Optional

from sqlalchemy import (
    ForeignKey,
    JSON,
    Numeric,
    String,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.mixins import TimestampMixin, pk_column

if TYPE_CHECKING:
    from app.models.user import User


class InvestmentPlan(Base, TimestampMixin):
    """Persisted user investment plan generated by the Investment Guide engine."""

    __tablename__ = "investment_plans"

    id: Mapped[int] = pk_column()
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    plan_name: Mapped[str] = mapped_column(String(100), nullable=False, default="Personalized Plan")
    total_amount: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False, default=Decimal("0.00"))
    monthly_sip: Mapped[Decimal] = mapped_column(Numeric(18, 2), nullable=False, default=Decimal("0.00"))
    risk_profile: Mapped[str] = mapped_column(String(20), nullable=False, default="moderate")
    horizon: Mapped[str] = mapped_column(String(20), nullable=False, default="3-5")
    financial_goal: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    emergency_reserve_status: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    preferred_assets: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    allocation: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    tree_data: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    scoring_metadata: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    # Relationships
    user: Mapped[User] = relationship("User", backref="investment_plans")
